version: "3.9"

services:
  db:
    image: postgres:17.6
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_v17:/var/lib/postgresql/data
      - /mnt/user/appdata/workload-tracker/backups:/backups
    restart: unless-stopped
    healthcheck:
      # Explicitly check a real database; libpq otherwise defaults to DB==USER
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: /mnt/user/appdata/workload-tracker/backend
      dockerfile: /mnt/user/appdata/workload-tracker/docker/backend/Dockerfile
      target: production
    env_file:
      - /boot/config/plugins/compose.manager/projects/workload-tracker/.env
    environment:
      - DEBUG=false
      - DJANGO_SETTINGS_MODULE=config.settings
      - ASYNC_JOBS=true
      # Allow cross-origin requests from your frontend. Set in .env, e.g.:
      # CORS_ALLOWED_ORIGINS=http://10.20.30.2:3000
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-}
      # Optional: allow all origins for quick LAN testing (do not use in production)
      - CORS_ALLOW_ALL_ORIGINS=${CORS_ALLOW_ALL_ORIGINS:-}
      # Optional: regex form, e.g. ^http://10\.20\.30\.2(:\d+)?$
      - CORS_ALLOWED_ORIGIN_REGEXES=${CORS_ALLOWED_ORIGIN_REGEXES:-}
      # Optional: custom headers list, comma-separated (rarely needed)
      - CORS_ALLOW_HEADERS=${CORS_ALLOW_HEADERS:-}
      # Optional convenience: set HOST_IP=10.20.30.2 to auto-allow http://HOST_IP:3000
      - HOST_IP=${HOST_IP:-}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/1
      - BACKUPS_DIR=/backups
      # On HTTP, disable cookie-based refresh; switch to true when behind HTTPS.
      - COOKIE_REFRESH_AUTH=${COOKIE_REFRESH_AUTH:-false}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - RUN_MIGRATIONS_ON_START=${RUN_MIGRATIONS_ON_START:-true}
      - SENTRY_DSN=${SENTRY_DSN}
      # Avoid HTTP→HTTPS redirect during local/LAN testing
      - SECURE_SSL_REDIRECT=${SECURE_SSL_REDIRECT:-false}
    volumes:
      - /mnt/user/appdata/workload-tracker/backups:/backups:rw
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --worker-class gthread --threads 4 --max-requests 1000 --max-requests-jitter 50
    healthcheck:
      test: ["CMD", "curl", "-fsS", "-H", "X-Forwarded-Proto: https", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "8000:8000"  # Host Nginx (Unraid) proxies to this

  worker:
    build:
      context: /mnt/user/appdata/workload-tracker/backend
      dockerfile: /mnt/user/appdata/workload-tracker/docker/backend/Dockerfile
      target: production
    env_file:
      - /boot/config/plugins/compose.manager/projects/workload-tracker/.env
    environment:
      - DEBUG=false
      - DJANGO_SETTINGS_MODULE=config.settings
      - ASYNC_JOBS=true
      - RUN_MIGRATIONS_ON_START=false
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/1
      - BACKUPS_DIR=/backups
      - COLLECT_STATIC=false
    command: celery -A config worker -l info --concurrency=2
    volumes:
      - /mnt/user/appdata/workload-tracker/backups:/backups
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker_db:
    build:
      context: /mnt/user/appdata/workload-tracker/backend
      dockerfile: /mnt/user/appdata/workload-tracker/docker/backend/Dockerfile
      target: production
    env_file:
      - /boot/config/plugins/compose.manager/projects/workload-tracker/.env
    environment:
      - DEBUG=false
      - DJANGO_SETTINGS_MODULE=config.settings
      - RUN_MIGRATIONS_ON_START=false
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/1
      - BACKUPS_DIR=/backups
      - COLLECT_STATIC=false
    command: celery -A config worker -l info --concurrency=1 -Q db_maintenance
    volumes:
      - /mnt/user/appdata/workload-tracker/backups:/backups
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker_beat:
    build:
      context: /mnt/user/appdata/workload-tracker/backend
      dockerfile: /mnt/user/appdata/workload-tracker/docker/backend/Dockerfile
      target: production
    env_file:
      - /boot/config/plugins/compose.manager/projects/workload-tracker/.env
    environment:
      - DEBUG=false
      - DJANGO_SETTINGS_MODULE=config.settings
      - ASYNC_JOBS=true
      - RUN_MIGRATIONS_ON_START=false
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379/1
      - BACKUPS_DIR=/backups
      - COLLECT_STATIC=false
      # Optional: explicit schedule path (defaults to /tmp/celerybeat-schedule)
      # - CELERY_BEAT_SCHEDULE_FILE=/tmp/celerybeat-schedule
    command: ["celery", "-A", "config", "beat", "-l", "INFO"]
    volumes:
      - /mnt/user/appdata/workload-tracker/backups:/backups
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: /mnt/user/appdata/workload-tracker/frontend
      dockerfile: /mnt/user/appdata/workload-tracker/docker/frontend/Dockerfile
      target: production
      args:
        # Point the frontend at the backend API directly when not using a reverse proxy.
        # Override via .env on Unraid: FRONTEND_API_URL=http://<unraid-ip>:8000/api
        VITE_API_URL: ${FRONTEND_API_URL:-/api}
        VITE_OPENAPI_MIGRATION_ENABLED: "true"
        # When not using HTTPS, disable cookie-based refresh and use localStorage tokens instead.
        # Override via .env on Unraid: FRONTEND_COOKIE_REFRESH_AUTH=false
        VITE_COOKIE_REFRESH_AUTH: ${FRONTEND_COOKIE_REFRESH_AUTH:-"false"}
    read_only: true
    tmpfs:
      - /tmp
    command: npx serve -s /app/_built -l 3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "3000:3000"  # Host Nginx (Unraid) proxies to this

volumes:
  postgres_data_v17:
  redis_data:
  static_volume:
  media_volume:
  frontend_build:
  beat_state:
