# Generated by Django 5.0.1 on 2025-08-28 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Tag',
                'verbose_name_plural': 'Skill Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(choices=[('strength', 'Strength'), ('development', 'Development'), ('learning', 'Learning')], max_length=20)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_used', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='people.person')),
                ('skill_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_skills', to='skills.skilltag')),
            ],
            options={
                'verbose_name': 'Person Skill',
                'verbose_name_plural': 'Person Skills',
                'ordering': ['skill_type', 'skill_tag__name'],
                'unique_together': {('person', 'skill_tag')},
            },
        ),
    ]
