# Generated by Django 5.0.1 on 2025-08-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personskill',
            unique_together={('person', 'skill_tag', 'skill_type')},
        ),
    ]
