# Generated by Django 5.2.6 on 2025-10-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_perf_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='personskill',
            name='personskill_person_skill_idx',
        ),
        migrations.RemoveIndex(
            model_name='personskill',
            name='personskill_skill_idx',
        ),
        migrations.RemoveIndex(
            model_name='skilltag',
            name='skilltag_name_lower_idx',
        ),
    ]
