# Generated by Django 5.2.6 on 2025-10-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_predeliverablesettings_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='project_active_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='project_active_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='projects_client_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectpredeliverablesettings',
            name='proj_pre_settings_proj_enabled',
        ),
        migrations.AlterField(
            model_name='projectpredeliverablesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
