# Generated by Django 5.2.10 on 2026-01-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrisk',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
