# Generated by Django 5.2.10 on 2026-01-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projectrisk_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrisk',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
