# Generated by Codex on 2026-01-30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_project_auto_hours_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_names_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
