# Generated by Codex on 2026-01-30
from django.db import migrations


def _rebuild_assigned_names(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Assignment = apps.get_model('assignments', 'Assignment')

    # Iterate active projects to avoid loading all at once
    qs = Project.objects.filter(is_active=True).only('id')
    for project in qs.iterator():
        names = (
            Assignment.objects
            .filter(project_id=project.id, is_active=True, person__is_active=True)
            .values_list('person__name', flat=True)
            .distinct()
        )
        cleaned = sorted({n.strip() for n in names if n and str(n).strip()}, key=lambda v: v.lower())
        text = ' '.join(cleaned)
        Project.objects.filter(id=project.id).update(assigned_names_text=text)


def _noop_reverse(apps, schema_editor):
    # No-op: backfill is safe and does not need rollback.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_project_assigned_names_text'),
        ('assignments', '0017_project_rollups'),
        ('people', '0009_deactivationaudit'),
    ]

    operations = [
        migrations.RunPython(_rebuild_assigned_names, _noop_reverse),
    ]
