# Generated by Django 5.2.6 on 2026-03-02

from django.db import migrations, models
from django.db.models import Q


SYSTEM_STATUSES = [
    {
        'key': 'planning',
        'label': 'Planning',
        'color_hex': '#60a5fa',
        'analytics_bucket': 'other',
        'sort_order': 10,
    },
    {
        'key': 'active',
        'label': 'Active',
        'color_hex': '#34d399',
        'analytics_bucket': 'active',
        'sort_order': 20,
    },
    {
        'key': 'active_ca',
        'label': 'Active CA',
        'color_hex': '#60a5fa',
        'analytics_bucket': 'active_ca',
        'sort_order': 30,
    },
    {
        'key': 'on_hold',
        'label': 'On Hold',
        'color_hex': '#f59e0b',
        'analytics_bucket': 'other',
        'sort_order': 40,
    },
    {
        'key': 'completed',
        'label': 'Completed',
        'color_hex': '#9ca3af',
        'analytics_bucket': 'other',
        'sort_order': 50,
    },
    {
        'key': 'cancelled',
        'label': 'Cancelled',
        'color_hex': '#ef4444',
        'analytics_bucket': 'other',
        'sort_order': 60,
    },
    {
        'key': 'inactive',
        'label': 'Inactive',
        'color_hex': '#64748b',
        'analytics_bucket': 'other',
        'sort_order': 70,
    },
]


def _normalize_status_key(value):
    return (value or '').strip().lower()


def _label_from_key(key):
    if key == 'active_ca':
        return 'Active CA'
    return key.replace('_', ' ').title()


def seed_status_definitions(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    ProjectStatusDefinition = apps.get_model('projects', 'ProjectStatusDefinition')

    Project.objects.filter(Q(status__isnull=True) | Q(status='')).update(status='inactive')

    distinct_statuses = list(Project.objects.order_by().values_list('status', flat=True).distinct())
    normalized_statuses = set()
    for raw in distinct_statuses:
        normalized = _normalize_status_key(raw)
        if not normalized:
            normalized = 'inactive'
        normalized_statuses.add(normalized)
        if raw != normalized:
            Project.objects.filter(status=raw).update(status=normalized)

    for item in SYSTEM_STATUSES:
        ProjectStatusDefinition.objects.update_or_create(
            key=item['key'],
            defaults={
                'label': item['label'],
                'color_hex': item['color_hex'],
                'analytics_bucket': item['analytics_bucket'],
                'is_system': True,
                'is_active': True,
                'sort_order': item['sort_order'],
            },
        )

    next_sort = 100
    for key in sorted(normalized_statuses):
        if ProjectStatusDefinition.objects.filter(key=key).exists():
            continue
        ProjectStatusDefinition.objects.create(
            key=key,
            label=_label_from_key(key),
            color_hex='#64748b',
            analytics_bucket='other',
            is_system=False,
            is_active=True,
            sort_order=next_sort,
        )
        next_sort += 10


def noop_reverse(apps, schema_editor):
    # Keep data in place on reverse migrations.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_restore_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatusDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('color_hex', models.CharField(default='#64748b', max_length=7)),
                ('analytics_bucket', models.CharField(choices=[('active', 'Active'), ('active_ca', 'Active CA'), ('other', 'Other')], default='other', max_length=16)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label', 'key'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='active', max_length=64),
        ),
        migrations.AddIndex(
            model_name='projectstatusdefinition',
            index=models.Index(fields=['is_active', 'sort_order'], name='proj_status_active_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstatusdefinition',
            index=models.Index(fields=['analytics_bucket'], name='proj_status_bucket_idx'),
        ),
        migrations.RunPython(seed_status_definitions, noop_reverse),
    ]
