# Generated by Django 5.2.6 on 2026-03-02

from django.db import migrations, models
from django.db.models import Q


def _forward_fill_analytics_flags(apps, schema_editor):
    ProjectStatusDefinition = apps.get_model('projects', 'ProjectStatusDefinition')

    ProjectStatusDefinition.objects.update(
        include_in_analytics=False,
        treat_as_ca_when_no_deliverable=False,
    )
    ProjectStatusDefinition.objects.filter(
        Q(analytics_bucket='active') | Q(analytics_bucket='active_ca')
    ).update(include_in_analytics=True)
    ProjectStatusDefinition.objects.filter(analytics_bucket='active_ca').update(
        treat_as_ca_when_no_deliverable=True,
    )


def _reverse_fill_analytics_bucket(apps, schema_editor):
    ProjectStatusDefinition = apps.get_model('projects', 'ProjectStatusDefinition')

    ProjectStatusDefinition.objects.update(analytics_bucket='other')
    ProjectStatusDefinition.objects.filter(include_in_analytics=True).update(analytics_bucket='active')
    ProjectStatusDefinition.objects.filter(treat_as_ca_when_no_deliverable=True).update(analytics_bucket='active_ca')


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_project_status_definitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatusdefinition',
            name='include_in_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectstatusdefinition',
            name='treat_as_ca_when_no_deliverable',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_forward_fill_analytics_flags, _reverse_fill_analytics_bucket),
        migrations.RemoveIndex(
            model_name='projectstatusdefinition',
            name='proj_status_bucket_idx',
        ),
        migrations.RemoveField(
            model_name='projectstatusdefinition',
            name='analytics_bucket',
        ),
        migrations.AddIndex(
            model_name='projectstatusdefinition',
            index=models.Index(fields=['include_in_analytics'], name='proj_status_include_ana_idx'),
        ),
    ]
