# Generated by Django 5.2.10 on 2026-03-04 22:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0020_remove_deliverableqataskedit_qa_task_and_more'),
        ('departments', '0006_department_secondary_managers'),
        ('people', '0010_restore_search_indexes'),
        ('projects', '0027_project_status_analytics_flags'),
        ('verticals', '0003_vertical_task_tracking_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('project', 'Project'), ('deliverable', 'Deliverable')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_task_templates', to='departments.department')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task_templates', to='verticals.vertical')),
            ],
            options={
                'ordering': ['vertical_id', 'scope', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('project', 'Project'), ('deliverable', 'Deliverable')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('completion_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignees', models.ManyToManyField(blank=True, related_name='project_tasks', to='people.person')),
                ('deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='deliverables.deliverable')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_tasks', to='departments.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='projects.project')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to='projects.projecttasktemplate')),
            ],
            options={
                'ordering': ['project_id', 'scope', 'deliverable_id', 'department_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='projecttasktemplate',
            index=models.Index(fields=['vertical', 'scope', 'is_active'], name='proj_task_tpl_vsi_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttasktemplate',
            index=models.Index(fields=['department', 'scope'], name='proj_task_tpl_dept_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'scope'], name='proj_task_project_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'deliverable'], name='proj_task_project_deliv_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['department', 'scope'], name='proj_task_dept_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='projecttask',
            constraint=models.CheckConstraint(condition=models.Q(('completion_percent__gte', 0), ('completion_percent__lte', 100)), name='proj_task_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='projecttask',
            constraint=models.CheckConstraint(condition=models.Q(('completion_percent__in', (0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100))), name='proj_task_percent_step_5'),
        ),
        migrations.AddConstraint(
            model_name='projecttask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'project'), ('deliverable__isnull', True)), models.Q(('scope', 'deliverable'), ('deliverable__isnull', False)), _connector='OR'), name='proj_task_scope_deliverable_consistency'),
        ),
    ]
