# Generated by Django 5.2.10 on 2026-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_projecttasktemplate_projecttask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='completion_mode',
            field=models.CharField(choices=[('percent', '0-100 Percent'), ('binary', 'Complete/Incomplete')], default='percent', max_length=20),
        ),
        migrations.AddField(
            model_name='projecttasktemplate',
            name='completion_mode',
            field=models.CharField(choices=[('percent', '0-100 Percent'), ('binary', 'Complete/Incomplete')], default='percent', max_length=20),
        ),
    ]
