# Generated by Django 5.0.1 on 2025-08-30 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('roles', '0002_auto_20250830_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role_fk',
            field=models.ForeignKey(blank=True, help_text="Person's role in the organization", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='roles.role'),
        ),
    ]
