# Generated by Django 5.0.1 on 2025-08-31 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_remove_person_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='role_fk',
            new_name='role',
        ),
    ]
