# Generated by Django 5.2.6 on 2025-10-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_search_lower_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='person_active_dept_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='person_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='person_name_lower_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='person_email_lower_idx',
        ),
    ]
