# Generated by Django 5.2.6 on 2026-03-01

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_deactivationaudit'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active', 'department'], name='person_active_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['updated_at'], name='person_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='person_name_lower_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(django.db.models.functions.text.Lower('email'), name='person_email_lower_idx'),
        ),
    ]
