# Generated by Django 5.2.6 on 2025-11-16 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=100)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='production', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('needs_reauth', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('extra_headers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('schema_version', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='EncryptedSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=36)),
                ('cipher_text', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='integrations.integrationconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=50)),
                ('celery_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='integrations.integrationconnection')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='integrations.integrationprovider')),
            ],
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='integrations.integrationprovider'),
        ),
        migrations.CreateModel(
            name='IntegrationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='integrations.integrationconnection')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='integrations.integrationconnection')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('projects', 'Projects'), ('clients', 'Clients')], max_length=50)),
                ('external_id', models.CharField(max_length=128)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='integrations.integrationconnection')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='integrations.integrationprovider')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'object_type', 'connection', 'external_id'), name='uniq_external_link')],
            },
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.UniqueConstraint(fields=('provider', 'company_id', 'environment'), name='uniq_integration_connection'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationrule',
            unique_together={('connection', 'object_key')},
        ),
        migrations.AlterUniqueTogether(
            name='integrationsetting',
            unique_together={('connection', 'key')},
        ),
    ]
