# Generated by Django 5.2.10 on 2026-03-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_restore_search_indexes'),
        ('departments', '0006_department_secondary_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentOrgChartLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_card_x', models.IntegerField(default=64)),
                ('department_card_y', models.IntegerField(default=48)),
                ('workspace_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_chart_layout', to='departments.department')),
            ],
            options={
                'verbose_name': 'Department Org Chart Layout',
            },
        ),
        migrations.CreateModel(
            name='DepartmentReportingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Reporting Group', max_length=120)),
                ('card_x', models.IntegerField(default=64)),
                ('card_y', models.IntegerField(default=240)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_groups', to='departments.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_reporting_groups', to='people.person')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['department', 'is_active', 'sort_order'], name='dept_rgroup_scope_idx'),
                    models.Index(fields=['department', 'manager'], name='dept_rgroup_manager_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(condition=models.Q(('is_active', True), ('manager__isnull', False)), fields=('department', 'manager'), name='uniq_active_reporting_group_manager_per_department'),
                ],
            },
        ),
        migrations.CreateModel(
            name='DepartmentReportingGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_group_memberships', to='departments.department')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_group_memberships', to='people.person')),
                ('reporting_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='departments.departmentreportinggroup')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['reporting_group', 'sort_order'], name='rgroup_member_order_idx'),
                    models.Index(fields=['department', 'person'], name='dept_rgroup_person_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('reporting_group', 'person'), name='uniq_reporting_group_person'),
                    models.UniqueConstraint(fields=('department', 'person'), name='uniq_department_reporting_group_person'),
                ],
            },
        ),
    ]
