from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    ProviderListView,
    ProviderDetailView,
    ProviderObjectCatalogView,
    ProviderCatalogView,
    ProviderCredentialView,
    ProviderResetView,
    ProviderConnectStartView,
    ProviderConnectCallbackView,
    MappingDefaultsView,
    IntegrationConnectionViewSet,
    IntegrationRuleViewSet,
    IntegrationRuleResyncView,
    IntegrationJobListView,
    IntegrationHealthView,
    IntegrationJobRetryView,
    IntegrationSecretKeyView,
    IntegrationConnectionTestView,
    IntegrationActivityTestView,
    ProjectMatchingSuggestionView,
    ProjectMatchingConfirmView,
)
from .azure_views import (
    AzureDirectoryDepartmentsView,
    AzureDirectoryGroupsView,
    AzureDepartmentMappingsView,
    AzureMigrationApplyView,
    AzureProvisioningReconcileNowView,
    AzureProvisioningValidateView,
    AzureProvisioningStatusView,
    AzureReconciliationConfirmView,
    AzureReconciliationListView,
    AzureReconciliationOverrideView,
    AzureReconciliationRefreshView,
    AzureReconciliationRejectView,
    AzureRoleMappingsView,
    AzureScimResourceTypesView,
    AzureScimSchemasView,
    AzureScimServiceProviderConfigView,
    AzureScimTokenView,
    AzureScimUserDetailView,
    AzureScimUsersView,
    AzureStatusView,
)

router = DefaultRouter()
router.register(r'connections', IntegrationConnectionViewSet, basename='integration-connection')
router.register(r'rules', IntegrationRuleViewSet, basename='integration-rule')

urlpatterns = [
    path('providers/', ProviderListView.as_view(), name='integration-providers'),
    path('providers/<str:key>/', ProviderDetailView.as_view(), name='integration-provider-detail'),
    path('providers/<str:key>/objects/', ProviderObjectCatalogView.as_view(), name='integration-provider-objects'),
    path('providers/<str:key>/catalog/', ProviderCatalogView.as_view(), name='integration-provider-catalog'),
    path('providers/<str:key>/credentials/', ProviderCredentialView.as_view(), name='integration-provider-credentials'),
    path('providers/<str:key>/connect/start/', ProviderConnectStartView.as_view(), name='integration-provider-connect-start'),
    path('providers/<str:key>/connect/callback/', ProviderConnectCallbackView.as_view(), name='integration-provider-connect-callback'),
    path('providers/<str:key>/reset/', ProviderResetView.as_view(), name='integration-provider-reset'),
    path('providers/<str:provider_key>/jobs/', IntegrationJobListView.as_view(), name='integration-provider-jobs'),
    path('jobs/<int:pk>/retry/', IntegrationJobRetryView.as_view(), name='integration-job-retry'),
    path('connections/<int:pk>/test/', IntegrationConnectionTestView.as_view(), name='integration-connection-test'),
    path('connections/<int:pk>/test-activity/', IntegrationActivityTestView.as_view(), name='integration-activity-test'),
    path('providers/<str:provider_key>/<str:object_key>/mapping/defaults/', MappingDefaultsView.as_view(), name='integration-mapping-defaults'),
    path('rules/<int:pk>/resync/', IntegrationRuleResyncView.as_view(), name='integration-rule-resync'),
    path('health/', IntegrationHealthView.as_view(), name='integration-health'),
    path('secret-key/', IntegrationSecretKeyView.as_view(), name='integration-secret-key'),
    path('providers/<str:provider_key>/projects/matching/suggestions/', ProjectMatchingSuggestionView.as_view(), name='integration-project-matching-suggestions'),
    path('providers/<str:provider_key>/projects/matching/confirm/', ProjectMatchingConfirmView.as_view(), name='integration-project-matching-confirm'),
    path('providers/azure/status/', AzureStatusView.as_view(), name='integration-azure-status'),
    path('providers/azure/scim/token/', AzureScimTokenView.as_view(), name='integration-azure-scim-token'),
    path('providers/azure/provisioning/status/', AzureProvisioningStatusView.as_view(), name='integration-azure-provisioning-status'),
    path('providers/azure/provisioning/validate/', AzureProvisioningValidateView.as_view(), name='integration-azure-provisioning-validate'),
    path('providers/azure/provisioning/reconcile-now/', AzureProvisioningReconcileNowView.as_view(), name='integration-azure-reconcile-now'),
    path('providers/azure/directory/departments/', AzureDirectoryDepartmentsView.as_view(), name='integration-azure-directory-departments'),
    path('providers/azure/directory/groups/', AzureDirectoryGroupsView.as_view(), name='integration-azure-directory-groups'),
    path('providers/azure/mappings/departments/', AzureDepartmentMappingsView.as_view(), name='integration-azure-mappings-departments'),
    path('providers/azure/mappings/roles/', AzureRoleMappingsView.as_view(), name='integration-azure-mappings-roles'),
    path('providers/azure/migration/reconciliation/', AzureReconciliationListView.as_view(), name='integration-azure-reconciliation'),
    path('providers/azure/migration/reconciliation/refresh/', AzureReconciliationRefreshView.as_view(), name='integration-azure-reconciliation-refresh'),
    path('providers/azure/migration/reconciliation/<int:id>/confirm/', AzureReconciliationConfirmView.as_view(), name='integration-azure-reconciliation-confirm'),
    path('providers/azure/migration/reconciliation/<int:id>/override/', AzureReconciliationOverrideView.as_view(), name='integration-azure-reconciliation-override'),
    path('providers/azure/migration/reconciliation/<int:id>/reject/', AzureReconciliationRejectView.as_view(), name='integration-azure-reconciliation-reject'),
    path('providers/azure/migration/apply/', AzureMigrationApplyView.as_view(), name='integration-azure-migration-apply'),
    path('providers/azure/scim/v2/ServiceProviderConfig', AzureScimServiceProviderConfigView.as_view(), name='integration-azure-scim-service-provider-config'),
    path('providers/azure/scim/v2/ServiceProviderConfig/', AzureScimServiceProviderConfigView.as_view(), name='integration-azure-scim-service-provider-config-slash'),
    path('providers/azure/scim/v2/Schemas', AzureScimSchemasView.as_view(), name='integration-azure-scim-schemas'),
    path('providers/azure/scim/v2/Schemas/', AzureScimSchemasView.as_view(), name='integration-azure-scim-schemas-slash'),
    path('providers/azure/scim/v2/ResourceTypes', AzureScimResourceTypesView.as_view(), name='integration-azure-scim-resource-types'),
    path('providers/azure/scim/v2/ResourceTypes/', AzureScimResourceTypesView.as_view(), name='integration-azure-scim-resource-types-slash'),
    path('providers/azure/scim/v2/Users', AzureScimUsersView.as_view(), name='integration-azure-scim-users'),
    path('providers/azure/scim/v2/Users/', AzureScimUsersView.as_view(), name='integration-azure-scim-users-slash'),
    path('providers/azure/scim/v2/Users/<str:principal_id>', AzureScimUserDetailView.as_view(), name='integration-azure-scim-user-detail'),
    path('providers/azure/scim/v2/Users/<str:principal_id>/', AzureScimUserDetailView.as_view(), name='integration-azure-scim-user-detail-slash'),
    path('', include(router.urls)),
]
