# Generated by Django 5.2.10 on 2026-03-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verticals', '0002_seed_verticals'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertical',
            name='task_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
