# Generated by Codex on 2026-03-05

from django.db import migrations


def enable_for_existing_templates(apps, schema_editor):
    Vertical = apps.get_model('verticals', 'Vertical')
    ProjectTaskTemplate = apps.get_model('projects', 'ProjectTaskTemplate')

    vertical_ids = (
        ProjectTaskTemplate.objects
        .values_list('vertical_id', flat=True)
        .distinct()
    )
    Vertical.objects.filter(id__in=vertical_ids, task_tracking_enabled=False).update(task_tracking_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_projecttasktemplate_projecttask_and_more'),
        ('verticals', '0003_vertical_task_tracking_enabled'),
    ]

    operations = [
        migrations.RunPython(enable_for_existing_templates, migrations.RunPython.noop),
    ]
