# Generated by Codex on 2026-03-05

from django.db import migrations, models


def enable_existing_verticals(apps, schema_editor):
    Vertical = apps.get_model('verticals', 'Vertical')
    Vertical.objects.filter(task_tracking_enabled=False).update(task_tracking_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('verticals', '0004_auto_enable_task_tracking_for_existing_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertical',
            name='task_tracking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(enable_existing_verticals, migrations.RunPython.noop),
    ]
