# Generated by Django 5.0.1 on 2025-08-27 21:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(blank=True, help_text='Completion percentage (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.CharField(blank=True, help_text='Brief description (e.g., SD, DD, IFP, IFC)', max_length=200)),
                ('date', models.DateField(blank=True, help_text='Target or actual date - can be removed if project on hold', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional details, owner info, requirements, etc.')),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_completed', models.BooleanField(default=False, help_text='Mark when deliverable is done')),
                ('completed_date', models.DateField(blank=True, help_text='When it was actually completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'percentage', 'date', 'created_at'],
            },
        ),
    ]
