# Generated by Django 5.0.1 on 2025-09-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours', models.JSONField(default=dict)),
                ('role_on_milestone', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='deliverables.deliverable')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_assignments', to='people.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

