# Generated by Django 5.2.6 on 2025-10-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0011_deliverable_completion_check'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliverable',
            name='deliverable_completed_implies_date',
        ),
        migrations.RemoveIndex(
            model_name='deliverable',
            name='deliv_proj_date_done_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliverable',
            name='deliv_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='predeliverableitem',
            name='pdi_gen_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='predeliverableitem',
            name='pdi_gen_date_active_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE deliverables_deliverableassignment "
                        "DROP COLUMN IF EXISTS weekly_hours"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='deliverableassignment',
                    name='weekly_hours',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='predeliverableitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='predeliverabletype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
