# Generated by Django 5.2.10 on 2026-03-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0019_alter_template_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverableqataskedit',
            name='qa_task',
        ),
        migrations.RemoveField(
            model_name='deliverableqataskedit',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='deliverabletask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='deliverabletask',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='deliverabletask',
            name='deliverable',
        ),
        migrations.RemoveField(
            model_name='deliverabletask',
            name='department',
        ),
        migrations.RemoveField(
            model_name='deliverabletask',
            name='qa_assigned_to',
        ),
        migrations.RemoveField(
            model_name='deliverabletask',
            name='template',
        ),
        migrations.RemoveField(
            model_name='deliverabletasktemplate',
            name='department',
        ),
        migrations.DeleteModel(
            name='DeliverableQATask',
        ),
        migrations.DeleteModel(
            name='DeliverableQATaskEdit',
        ),
        migrations.DeleteModel(
            name='DeliverableTask',
        ),
        migrations.DeleteModel(
            name='DeliverableTaskTemplate',
        ),
    ]
