# Generated by Django 5.0.1 on 2025-08-26 20:30

from django.db import migrations, models
from datetime import datetime, timedelta


def convert_percentage_to_hours(apps, schema_editor):
    """Convert existing percentage allocations to weekly hours for 12 weeks"""
    Assignment = apps.get_model('assignments', 'Assignment')
    
    # Get current date and calculate next 12 Sunday dates
    today = datetime.now().date()
    current_sunday = today - timedelta(days=(today.weekday() + 1) % 7)
    
    week_sundays = []
    for i in range(12):
        week_sundays.append(current_sunday.strftime('%Y-%m-%d'))
        current_sunday += timedelta(days=7)
    
    for assignment in Assignment.objects.all():
        if assignment.allocation_percentage > 0:
            # Calculate weekly hours based on percentage and person's capacity
            weekly_capacity = assignment.person.weekly_capacity
            weekly_hours_value = (weekly_capacity * assignment.allocation_percentage) / 100
            
            # Set the same hours for all 12 weeks
            assignment.weekly_hours = {week: weekly_hours_value for week in week_sundays}
            assignment.save()


def reverse_conversion(apps, schema_editor):
    """Reverse migration - convert back to percentage if needed"""
    Assignment = apps.get_model('assignments', 'Assignment')
    
    for assignment in Assignment.objects.all():
        if assignment.weekly_hours:
            # Calculate average weekly hours and convert back to percentage
            hours_values = [h for h in assignment.weekly_hours.values() if h > 0]
            if hours_values:
                avg_hours = sum(hours_values) / len(hours_values)
                percentage = min(100, int((avg_hours / assignment.person.weekly_capacity) * 100))
                assignment.allocation_percentage = percentage
                assignment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='weekly_hours',
            field=models.JSONField(default=dict, help_text='Hours per week for 12-week period'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='allocation_percentage',
            field=models.IntegerField(default=0, help_text='Legacy percentage field'),
        ),
        migrations.RunPython(convert_percentage_to_hours, reverse_conversion),
    ]
