# Generated by Django 5.0.1 on 2025-08-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_retrofit_weekly_hours'),
        ('projects', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
