# Generated by Django 5.2.6 on 2025-10-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignment_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assignment',
            name='assign_active_person_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='assign_active_project_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='assign_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignment',
            name='asn_person_active_idx',
        ),
    ]
