# Generated by Django 5.2.10 on 2026-01-29 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0016_allow_assignment_person_null'),
        ('projects', '0020_project_auto_hours_template'),
        ('departments', '0003_department_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWeeklyHoursRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Sunday ISO date key (UTC)')),
                ('person_hours', models.FloatField(default=0.0)),
                ('placeholder_hours', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_hours_rollups', to='departments.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_hours_rollups', to='projects.project')),
            ],
            options={
                'ordering': ['-week_start', 'project_id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignmentCountsRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_count', models.PositiveIntegerField(default=0)),
                ('placeholder_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_counts_rollups', to='departments.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_counts_rollups', to='projects.project')),
            ],
            options={
                'ordering': ['project_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectweeklyhoursrollup',
            constraint=models.UniqueConstraint(fields=('project', 'department', 'week_start'), name='uniq_project_weekly_hours_rollup'),
        ),
        migrations.AddConstraint(
            model_name='projectassignmentcountsrollup',
            constraint=models.UniqueConstraint(fields=('project', 'department'), name='uniq_project_assignment_counts_rollup'),
        ),
        migrations.AddIndex(
            model_name='projectweeklyhoursrollup',
            index=models.Index(fields=['week_start'], name='idx_pwh_week_start'),
        ),
        migrations.AddIndex(
            model_name='projectweeklyhoursrollup',
            index=models.Index(fields=['project', 'week_start'], name='idx_pwh_project_week'),
        ),
        migrations.AddIndex(
            model_name='projectweeklyhoursrollup',
            index=models.Index(fields=['department', 'week_start'], name='idx_pwh_dept_week'),
        ),
        migrations.AddIndex(
            model_name='projectassignmentcountsrollup',
            index=models.Index(fields=['project'], name='idx_pac_project'),
        ),
        migrations.AddIndex(
            model_name='projectassignmentcountsrollup',
            index=models.Index(fields=['department'], name='idx_pac_department'),
        ),
    ]
