# Generated by Django 5.2.6 on 2026-03-01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0017_project_rollups'),
        ('departments', '0006_department_secondary_managers'),
        ('people', '0009_deactivationaudit'),
        ('projects', '0024_project_vertical'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentWeekHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Canonical Sunday ISO date')),
                ('hours', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_hours', to='assignments.assignment')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_week_hours', to='departments.department')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_week_hours', to='people.person')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_week_hours', to='projects.project')),
            ],
            options={
                'ordering': ['assignment_id', 'week_start'],
            },
        ),
        migrations.AddConstraint(
            model_name='assignmentweekhour',
            constraint=models.UniqueConstraint(fields=('assignment', 'week_start'), name='uniq_assignment_week_hours'),
        ),
        migrations.AddIndex(
            model_name='assignmentweekhour',
            index=models.Index(fields=['assignment', 'week_start'], name='idx_awh_assignment_week'),
        ),
        migrations.AddIndex(
            model_name='assignmentweekhour',
            index=models.Index(fields=['person', 'week_start'], name='idx_awh_person_week'),
        ),
        migrations.AddIndex(
            model_name='assignmentweekhour',
            index=models.Index(fields=['project', 'week_start'], name='idx_awh_project_week'),
        ),
        migrations.AddIndex(
            model_name='assignmentweekhour',
            index=models.Index(fields=['department', 'week_start'], name='idx_awh_department_week'),
        ),
        migrations.AddIndex(
            model_name='assignmentweekhour',
            index=models.Index(fields=['week_start'], name='idx_awh_week_start'),
        ),
    ]
