# Generated by Django 5.2.10 on 2026-03-01 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0018_assignmentweekhour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectweeklyhoursrollup',
            name='person_hours',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='projectweeklyhoursrollup',
            name='placeholder_hours',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
