# Generated by Django 5.0.1 on 2025-08-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role name (e.g., Senior Engineer, Product Manager)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the role responsibilities')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is currently available for assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
    ]
