# Generated by Django 5.0.1 on 2025-08-30 23:31

from django.db import migrations


def create_default_roles(apps, schema_editor):
    """Create default roles for the organization"""
    Role = apps.get_model('roles', 'Role')
    
    default_roles = [
        {
            'name': 'Engineer',
            'description': 'Software Engineer - develops and maintains software systems',
            'is_active': True,
        },
        {
            'name': 'Senior Engineer',
            'description': 'Senior Software Engineer - leads technical initiatives and mentors junior engineers',
            'is_active': True,
        },
        {
            'name': 'Staff Engineer',
            'description': 'Staff Engineer - provides technical leadership across multiple teams',
            'is_active': True,
        },
        {
            'name': 'Principal Engineer',
            'description': 'Principal Engineer - sets technical direction and architecture standards',
            'is_active': True,
        },
        {
            'name': 'Engineering Manager',
            'description': 'Engineering Manager - manages engineering teams and delivery',
            'is_active': True,
        },
        {
            'name': 'Product Manager',
            'description': 'Product Manager - defines product requirements and roadmap',
            'is_active': True,
        },
        {
            'name': 'Designer',
            'description': 'UI/UX Designer - designs user interfaces and experiences',
            'is_active': True,
        },
        {
            'name': 'QA Engineer',
            'description': 'Quality Assurance Engineer - tests software and ensures quality',
            'is_active': True,
        },
        {
            'name': 'DevOps Engineer',
            'description': 'DevOps Engineer - manages infrastructure and deployment pipelines',
            'is_active': True,
        },
        {
            'name': 'Data Analyst',
            'description': 'Data Analyst - analyzes data and creates reports',
            'is_active': True,
        },
    ]
    
    for role_data in default_roles:
        Role.objects.get_or_create(
            name=role_data['name'],
            defaults={
                'description': role_data['description'],
                'is_active': role_data['is_active'],
            }
        )


def reverse_default_roles(apps, schema_editor):
    """Remove default roles"""
    Role = apps.get_model('roles', 'Role')
    default_role_names = [
        'Engineer', 'Senior Engineer', 'Staff Engineer', 'Principal Engineer',
        'Engineering Manager', 'Product Manager', 'Designer', 'QA Engineer',
        'DevOps Engineer', 'Data Analyst'
    ]
    Role.objects.filter(name__in=default_role_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles, reverse_default_roles),
    ]
