# Generated by Django 5.2.6 on 2025-10-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_utilization_scheme'),
    ]

    operations = [
        # Ensure column "key" exists on core_utilizationscheme and is unique
        migrations.RunSQL(
            sql=r'''
DO $$
BEGIN
    -- Add column if missing
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'core_utilizationscheme'
          AND column_name = 'key'
    ) THEN
        ALTER TABLE core_utilizationscheme ADD COLUMN key varchar(20);
    END IF;
END $$;
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
UPDATE core_utilizationscheme
SET key = COALESCE(NULLIF(key, ''), 'default')
WHERE key IS NULL OR key = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=r"""
CREATE UNIQUE INDEX IF NOT EXISTS core_utilizationscheme_key_uniq
ON core_utilizationscheme(key);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
