# Generated by Codex on 2026-01-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_calendar_feed_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentProjectRole',
        ),
    ]
