# Generated by Django 5.2.10 on 2026-01-28 21:47

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_deliverable_phase_definitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizationscheme',
            name='full_capacity_hours',
            field=models.PositiveIntegerField(default=36),
        ),
        migrations.AlterField(
            model_name='autohourstemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='autohourstemplate',
            name='phase_keys',
            field=models.JSONField(blank=True, default=core.models.default_auto_hours_phase_keys),
        ),
        migrations.AlterField(
            model_name='autohourstemplaterolesetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliverablephasedefinition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliverablephasedefinition',
            name='range_max',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='deliverablephasedefinition',
            name='range_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
