# Generated by Django 5.2.10 on 2026-01-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_full_capacity_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='autohourstemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
