# Generated by Django 5.2.10 on 2026-01-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_project_template_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='autohourstemplate',
            name='excluded_department_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='autohourstemplate',
            name='excluded_role_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
