# Generated by Django 5.2.10 on 2026-01-29 00:49

from django.db import migrations, models


def forwards_copy_exclusions(apps, schema_editor):
    AutoHoursTemplate = apps.get_model('core', 'AutoHoursTemplate')
    ProjectRole = apps.get_model('projects', 'ProjectRole')
    Department = apps.get_model('departments', 'Department')

    for template in AutoHoursTemplate.objects.all():
        role_ids = list(getattr(template, 'excluded_role_ids', []) or [])
        dept_ids = list(getattr(template, 'excluded_department_ids', []) or [])
        if role_ids:
            roles = list(ProjectRole.objects.filter(id__in=role_ids))
            if roles:
                template.excluded_roles.add(*roles)
        if dept_ids:
            departments = list(Department.objects.filter(id__in=dept_ids))
            if departments:
                template.excluded_departments.add(*departments)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_template_exclusions'),
        ('projects', '0020_project_auto_hours_template'),
        ('departments', '0003_department_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='autohourstemplate',
            name='excluded_roles',
            field=models.ManyToManyField(blank=True, related_name='auto_hours_template_exclusions', to='projects.projectrole'),
        ),
        migrations.AddField(
            model_name='autohourstemplate',
            name='excluded_departments',
            field=models.ManyToManyField(blank=True, related_name='auto_hours_template_exclusions', to='departments.department'),
        ),
        migrations.RunPython(forwards_copy_exclusions, noop_reverse),
        migrations.RemoveField(
            model_name='autohourstemplate',
            name='excluded_role_ids',
        ),
        migrations.RemoveField(
            model_name='autohourstemplate',
            name='excluded_department_ids',
        ),
    ]
