# Generated by Django 5.2.10 on 2026-01-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_hours_template_exclusions_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoHoursGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=20, unique=True)),
                ('weeks_by_phase', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto Hours Global Settings',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='autohourstemplate',
            name='weeks_by_phase',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
