# Generated by Django 5.2.10 on 2026-01-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_auto_hours_weeks_by_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='autohourstemplaterolesetting',
            name='role_count_by_phase',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
