# Generated by Django 5.2.10 on 2026-01-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_role_count_by_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='autohoursrolesetting',
            name='role_count_by_phase',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
