# Generated by Django 5.2.10 on 2026-02-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_jobaccessrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobaccessrecord',
            new_name='core_jobacc_created_ff3037_idx',
            old_name='core_jobacc_created_429d3f_idx',
        ),
    ]
