# Generated by Django 5.2.10 on 2026-03-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_webpushglobalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushVapidKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=20, unique=True)),
                ('encrypted_public_key', models.BinaryField(blank=True, default=b'')),
                ('encrypted_private_key', models.BinaryField(blank=True, default=b'')),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Web Push VAPID Keys',
                'ordering': ['key'],
            },
        ),
    ]
