# Generated by Django 5.2.10 on 2026-03-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_webpushvapidkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_assignment_changes_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_daily_digest_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_pre_deliverable_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
