# Generated by Django 5.2.10 on 2026-03-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_webpushglobalsettings_push_assignment_changes_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='push_deliverable_date_changes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_deliverable_date_change_scope',
            field=models.CharField(choices=[('next_upcoming', 'Next upcoming deliverable only'), ('all_upcoming', 'All upcoming deliverables')], default='next_upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_deliverable_date_change_within_two_weeks_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_deliverable_date_changes_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
