# Generated by Django 5.2.10 on 2026-03-06 14:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_notificationpreference_push_deliverable_date_changes_and_more'),
        ('projects', '0029_projecttask_completion_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='push_digest_window',
            field=models.CharField(choices=[('instant', 'Instant'), ('morning', 'Morning digest'), ('evening', 'Evening digest')], default='instant', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_quiet_hours_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_quiet_hours_end',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_quiet_hours_start',
            field=models.PositiveSmallIntegerField(default=22, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_snooze_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_weekend_mute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_rate_limit_per_hour',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.CreateModel(
            name='WebPushDeferredNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, default='', max_length=120)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('quiet_hours', 'Quiet hours'), ('weekend', 'Weekend mute'), ('snooze', 'Snoozed'), ('rate_limit', 'Rate limited'), ('digest_window', 'Digest window')], max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('deliver_after', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferred_web_push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deliver_after', 'id'],
                'indexes': [models.Index(fields=['deliver_after'], name='idx_push_def_deliver_after'), models.Index(fields=['user', 'deliver_after'], name='idx_push_def_user_deliver'), models.Index(fields=['project_id', 'deliver_after'], name='idx_push_def_project_deliver')],
            },
        ),
        migrations.CreateModel(
            name='WebPushProjectMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_user_mutes', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_project_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-muted_until', '-id'],
                'indexes': [models.Index(fields=['user', 'muted_until'], name='idx_push_mute_user_until'), models.Index(fields=['project', 'muted_until'], name='idx_push_mute_proj_until')],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
