# Generated by Django 5.2.10 on 2026-03-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_notificationpreference_push_digest_window_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='push_actions_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_deep_links_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_digest_window_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_rate_limit_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_snooze_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_subscription_cleanup_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_actions_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_deep_links_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_digest_window_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_quiet_hours_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_rate_limit_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_snooze_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_subscription_healthcheck_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='push_weekend_mute_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
