# Generated by hand for notifications unification.

from __future__ import annotations

from datetime import timedelta

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def _default_matrix():
    return {
        'pred.reminder': {'mobilePush': True, 'email': True, 'inBrowser': True},
        'pred.digest': {'mobilePush': True, 'email': True, 'inBrowser': True},
        'assignment.created': {'mobilePush': True, 'email': True, 'inBrowser': True},
        'assignment.removed': {'mobilePush': True, 'email': True, 'inBrowser': True},
        'assignment.bulk_updated': {'mobilePush': True, 'email': True, 'inBrowser': True},
        'deliverable.reminder': {'mobilePush': True, 'email': True, 'inBrowser': True},
        'deliverable.date_changed': {'mobilePush': True, 'email': True, 'inBrowser': True},
    }


def _in_app_default_expiry():
    return timezone.now() + timedelta(days=7)


def backfill_notification_channel_matrices(apps, schema_editor):
    NotificationPreference = apps.get_model('core', 'NotificationPreference')
    WebPushGlobalSettings = apps.get_model('core', 'WebPushGlobalSettings')

    for pref in NotificationPreference.objects.all().iterator():
        matrix = _default_matrix()

        matrix['pred.reminder']['mobilePush'] = bool(getattr(pref, 'push_pre_deliverable_reminders', True))
        matrix['pred.digest']['mobilePush'] = bool(getattr(pref, 'push_daily_digest', False))

        assignment_mobile = bool(getattr(pref, 'push_assignment_changes', True))
        matrix['assignment.created']['mobilePush'] = assignment_mobile
        matrix['assignment.removed']['mobilePush'] = assignment_mobile
        matrix['assignment.bulk_updated']['mobilePush'] = assignment_mobile

        matrix['deliverable.date_changed']['mobilePush'] = bool(
            getattr(pref, 'push_deliverable_date_changes', True)
        )

        matrix['pred.reminder']['email'] = bool(getattr(pref, 'email_pre_deliverable_reminders', True))
        matrix['pred.digest']['email'] = bool(getattr(pref, 'daily_digest', False))

        pref.notification_channel_matrix = matrix
        pref.save(update_fields=['notification_channel_matrix'])

    for cfg in WebPushGlobalSettings.objects.all().iterator():
        matrix = _default_matrix()
        matrix['pred.reminder']['mobilePush'] = bool(
            getattr(cfg, 'push_pre_deliverable_reminders_enabled', True)
        )
        matrix['pred.digest']['mobilePush'] = bool(
            getattr(cfg, 'push_daily_digest_enabled', True)
        )

        assignment_mobile = bool(getattr(cfg, 'push_assignment_changes_enabled', True))
        matrix['assignment.created']['mobilePush'] = assignment_mobile
        matrix['assignment.removed']['mobilePush'] = assignment_mobile
        matrix['assignment.bulk_updated']['mobilePush'] = assignment_mobile

        matrix['deliverable.date_changed']['mobilePush'] = bool(
            getattr(cfg, 'push_deliverable_date_changes_enabled', True)
        )

        cfg.notification_channel_matrix = matrix
        cfg.save(update_fields=['notification_channel_matrix'])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_notificationpreference_push_actions_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='notification_channel_matrix',
            field=models.JSONField(blank=True, default=_default_matrix),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='notification_channel_matrix',
            field=models.JSONField(blank=True, default=_default_matrix),
        ),
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='/', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=_in_app_default_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(fields=['user', 'cleared_at', 'created_at'], name='idx_inapp_user_clear'),
                    models.Index(fields=['user', 'read_at', 'created_at'], name='idx_inapp_user_read'),
                    models.Index(fields=['expires_at'], name='idx_inapp_expires'),
                ],
            },
        ),
        migrations.CreateModel(
            name='EmailNotificationDigestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='/', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='email_notification_digest_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [
                    models.Index(fields=['user', 'sent_at', 'created_at'], name='idx_emaildig_user_sent'),
                    models.Index(fields=['sent_at', 'created_at'], name='idx_emaildig_sent'),
                ],
            },
        ),
        migrations.RunPython(backfill_notification_channel_matrices, noop_reverse),
    ]
