# Generated by Django 5.2.10 on 2026-03-06 16:36

import core.models
import core.notification_matrix
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_notification_channels_and_inapp_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='expires_at',
            field=models.DateTimeField(default=core.models.default_in_app_notification_expiry),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_channel_matrix',
            field=models.JSONField(blank=True, default=core.notification_matrix.default_notification_channel_matrix),
        ),
        migrations.AlterField(
            model_name='webpushglobalsettings',
            name='notification_channel_matrix',
            field=models.JSONField(blank=True, default=core.notification_matrix.default_notification_channel_matrix),
        ),
    ]
