# Generated by Django 5.2.10 on 2026-03-06 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_notification_preference_opt_in_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='push_quiet_hours_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='push_quiet_hours_end',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='push_quiet_hours_start',
            field=models.PositiveSmallIntegerField(default=17, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
