# Generated by Django 5.2.10 on 2026-03-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_notificationpreference_push_quiet_hours_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='push_weekend_mute',
            field=models.BooleanField(default=True),
        ),
    ]
