# Generated by Django 5.2.10 on 2026-03-06 20:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


EVENT_TEMPLATE_DEFAULTS = [
    {
        'event_key': 'pred.reminder',
        'label': 'Pre-deliverable reminder',
        'description': 'Reminder for upcoming pre-deliverable work.',
    },
    {
        'event_key': 'pred.digest',
        'label': 'Daily digest',
        'description': 'Daily summary of your relevant pre-deliverables.',
    },
    {
        'event_key': 'assignment.created',
        'label': 'Assignment created',
        'description': 'A new assignment was created for your linked person.',
    },
    {
        'event_key': 'assignment.removed',
        'label': 'Assignment removed',
        'description': 'An assignment was removed for your linked person.',
    },
    {
        'event_key': 'assignment.bulk_updated',
        'label': 'Assignment bulk updated',
        'description': 'Bulk assignment updates affected your linked person.',
    },
    {
        'event_key': 'deliverable.reminder',
        'label': 'Deliverable reminder',
        'description': 'Reminder for upcoming deliverables on your assigned projects.',
    },
    {
        'event_key': 'deliverable.date_changed',
        'label': 'Deliverable date changed',
        'description': 'A project deliverable date changed for an assigned project.',
    },
]


def seed_notification_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model('core', 'NotificationTemplate')
    existing = set(
        NotificationTemplate.objects.values_list('event_key', flat=True)
    )
    rows = []
    for item in EVENT_TEMPLATE_DEFAULTS:
        event_key = str(item['event_key'])
        if event_key in existing:
            continue
        label = str(item['label'])
        description = str(item['description'])
        rows.append(
            NotificationTemplate(
                event_key=event_key,
                push_title_template=label,
                push_body_template=description,
                email_subject_template=f"{label} - Workload Tracker",
                email_body_template=description,
                in_app_title_template=label,
                in_app_body_template=description,
                push_ttl_seconds=3600,
                push_urgency='normal',
                push_topic_mode='event',
            )
        )
    if rows:
        NotificationTemplate.objects.bulk_create(rows, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_notificationpreference_push_weekend_mute'),
        ('projects', '0029_projecttask_completion_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('mobilePush', 'Mobile Push'), ('email', 'Email'), ('inBrowser', 'In Browser')], max_length=32)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('queued', 'Queued'), ('deferred', 'Deferred'), ('suppressed', 'Suppressed'), ('failed', 'Failed'), ('opened', 'Opened'), ('cleared', 'Cleared'), ('read', 'Read')], max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationProjectMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_push_muted_until', models.DateTimeField(blank=True, null=True)),
                ('email_muted_until', models.DateTimeField(blank=True, null=True)),
                ('in_browser_muted_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=120, unique=True)),
                ('push_title_template', models.CharField(blank=True, default='', max_length=200)),
                ('push_body_template', models.TextField(blank=True, default='')),
                ('email_subject_template', models.CharField(blank=True, default='', max_length=200)),
                ('email_body_template', models.TextField(blank=True, default='')),
                ('in_app_title_template', models.CharField(blank=True, default='', max_length=200)),
                ('in_app_body_template', models.TextField(blank=True, default='')),
                ('push_ttl_seconds', models.PositiveIntegerField(default=3600, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(2419200)])),
                ('push_urgency', models.CharField(choices=[('very-low', 'Very Low'), ('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=16)),
                ('push_topic_mode', models.CharField(choices=[('none', 'None'), ('event', 'Event'), ('project', 'Project')], default='event', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_key'],
            },
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='channel_origin',
            field=models.CharField(blank=True, default='inBrowser', max_length=40),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='delivery_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='active_web_suppression_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='active_web_window_seconds',
            field=models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(3600)]),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='in_app_retention_days',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='webpushglobalsettings',
            name='saved_in_app_retention_days',
            field=models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(3650)]),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['user', 'is_saved', 'created_at'], name='idx_inapp_user_saved'),
        ),
        migrations.AddField(
            model_name='notificationdeliverylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_delivery_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationprojectmute',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user_mutes', to='projects.project'),
        ),
        migrations.AddField(
            model_name='notificationprojectmute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_project_mutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notification_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(fields=['created_at'], name='idx_ndl_created'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(fields=['event_key', 'created_at'], name='idx_ndl_event_created'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(fields=['channel', 'status', 'created_at'], name='idx_ndl_chan_stat_created'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliverylog',
            index=models.Index(fields=['user', 'created_at'], name='idx_ndl_user_created'),
        ),
        migrations.AddIndex(
            model_name='notificationprojectmute',
            index=models.Index(fields=['user', 'updated_at'], name='idx_npm_user_updated'),
        ),
        migrations.AddIndex(
            model_name='notificationprojectmute',
            index=models.Index(fields=['project', 'updated_at'], name='idx_npm_project_updated'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationprojectmute',
            unique_together={('user', 'project')},
        ),
        migrations.RunPython(seed_notification_templates, noop_reverse),
    ]
