# Generated by Django 5.2.5 on 2026-03-06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_notificationdeliverylog_notificationprojectmute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupAutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=20, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=16)),
                ('schedule_day_of_week', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('schedule_day_of_month', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('schedule_hour', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('schedule_minute', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('schedule_timezone', models.CharField(default='UTC', max_length=64)),
                ('backups_dir', models.CharField(default='/backups', max_length=1024)),
                ('retention_daily', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('retention_weekly', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(104)])),
                ('retention_monthly', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)])),
                ('last_automatic_backup_at', models.DateTimeField(blank=True, null=True)),
                ('last_automatic_backup_filename', models.CharField(blank=True, default='', max_length=255)),
                ('next_automatic_backup_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Automation Settings',
                'ordering': ['key'],
            },
        ),
    ]

