# Generated by Django 5.2.10 on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_backupautomationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureToggleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=20, unique=True)),
                ('reporting_groups_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Toggle Settings',
                'ordering': ['key'],
            },
        ),
    ]
