# Generated by Django 5.2.10 on 2026-03-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_featuretogglesettings"),
        ("core", "0056_projectvisibilitysettings"),
    ]

    operations = []
